project_id = "mikltjgbvxrxndtszorb"

[functions.create-donation-payment]
verify_jwt = false

[functions.submit-waitlist]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.sovereign-ai-core]
verify_jwt = true