project_id = "mikltjgbvxrxndtszorb"

[functions.send-feedback]
verify_jwt = false

[functions.create-donation-payment]
verify_jwt = false

[functions.submit-waitlist]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.aura-core]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

[functions.voice-synthesis]
verify_jwt = true

[functions.ingest-event]
verify_jwt = true

[functions.aura-emit]
verify_jwt = true

[functions.aura-autonomous-platform]
verify_jwt = true

[functions.admin-broadcast]
verify_jwt = true

[functions.admin-override]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = true