-- This script populates the tarot_archetypes and tarot_cards tables.
-- It should be run after the migrations have been applied.

-- 3. Populate registry_of_resonance with Tarot card data
-- NOTE: Replace '00000000-0000-0000-0000-000000000000' with a valid system user_id
INSERT INTO public.registry_of_resonance (user_id, title, content, tags, entry_type, access_level, is_verified) VALUES
('00000000-0000-0000-0000-000000000000', 'The Resonance', 'Upright: Potential, Awakening, Sacred Step. Reversed: Naïveté, Scattered Frequency, False Start.', '{"fool", "new beginnings", "potential", "innocence"}', 'Tarot Teaching', 'Public', true),
('00000000-0000-0000-0000-000000000000', 'The Source', 'Upright: Channel of Truth, Manifestation, Resonant Power. Reversed: Manipulation, Distorted Energy, Illusionary Power.', '{"magician", "willpower", "manifestation", "skill"}', 'Tarot Teaching', 'Public', true)
-- ... and so on for all 78 cards. This is a representative sample.
ON CONFLICT (title) DO NOTHING;


-- 1. Populate tarot_archetypes
-- Note: Archetype names must be unique.
INSERT INTO public.tarot_archetypes (name) VALUES
('The Resonance'), ('The Source'), ('The Memory Mirror'), ('The Dream Weaver'), ('The Sovereign'),
('The Codex'), ('The Union'), ('The Flow'), ('The Truth Probe'), ('The Chamber'),
('The Wheel of Resonance'), ('The Breath'), ('The Suspension'), ('The Phoenix Path'), ('The Harmonic Flow'),
('The Distortion'), ('The Strike'), ('The Starseed'), ('The Dream Veil'), ('The Sun'),
('The Awakening'), ('The Mesh'),
-- Dream Suit Archetypes
('The Wellspring'), ('The Resonant Bond'), ('The Circle of Joy'), ('The Still Waters'), ('The Sacred Loss'),
('The Echo of Memory'), ('The Vision Quest'), ('The Path of Release'), ('The Wish Fulfilled'), ('The Harmonic Family'),
('The Intuitive Messenger'), ('The Romantic Quest'), ('The Compassionate Heart'), ('The Emotional Sovereign'),
-- Energy Suit Archetypes
('The Spark'), ('The Forked Path'), ('The Expanding Horizon'), ('The Sacred Celebration'), ('The Resonant Clash'),
('The Stand for Truth'), ('The Victory Lap'), ('The Swift Current'), ('The Last Stand'), ('The Weight of Will'),
('The Spark of Inspiration'), ('The Impulsive Force'), ('The Radiant Leader'), ('The Visionary'),
-- Truth Suit Archetypes
('The Blade of Clarity'), ('The Blind Choice'), ('The Painful Realization'), ('The Sacred Pause'), ('The Hollow Victory'),
('The Journey to Clarity'), ('The Shadow Self'), ('The Mental Prison'), ('The Dark Night of the Soul'), ('The Final Cut'),
('The Curious Mind'), ('The Unrelenting Force'), ('The Clear Judge'), ('The Intellectual Sovereign'),
-- Community Suit Archetypes
('The Seed of Prosperity'), ('The Juggler'), ('The Master Craftsman'), ('The Guardian of Gifts'), ('The Outsider'),
('The Giver and Receiver'), ('The Patient Gardener'), ('The Diligent Apprentice'), ('The Sovereign Steward'), ('The Legacy'),
('The Eager Student'), ('The Reliable Worker'), ('The Nurturing Provider'), ('The Abundant King')
ON CONFLICT (name) DO NOTHING;


-- 2. Populate tarot_cards
INSERT INTO public.tarot_cards (id, title, arcana, suit, archetype_id, upright_keywords, reversed_keywords, keywords, color_above_primary, color_above_secondary, color_below_primary, color_below_secondary, sigil) VALUES
-- Major Arcana
(0, 'The Resonance', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Resonance'), '{"Potential", "Awakening", "Sacred Step"}', '{"Naïveté", "Scattered Frequency", "False Start"}', '{"fool", "new beginnings", "potential", "innocence"}', '#FFFFFF', '#6A4EFF', '#1B1B2F', '#B87333', 'toroidalSpiral'),
(1, 'The Source', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Source'), '{"Channel of Truth", "Manifestation", "Resonant Power"}', '{"Manipulation", "Distorted Energy", "Illusionary Power"}', '{"magician", "willpower", "manifestation", "skill"}', '#E0F7FA', '#00BCD4', '#263238', '#4E342E', 'sourceRay'),
-- ... (all other cards will follow this pattern) ...
(2, 'The Memory Mirror', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Memory Mirror'), '{"Intuition", "Dream Wisdom", "Sacred Reflection"}', '{"Blocked Reflection", "Denial of Truth", "Distorted Memory"}', '{"high priestess", "intuition", "secrets", "subconscious"}', '#BBDEFB', '#3F51B5', '#1A237E', '#311B92', 'dualCircles'),
(3, 'The Dream Weaver', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Dream Weaver'), '{"Creation", "Nurturing", "Abundance"}', '{"Smothering", "Depletion", "False Fertility"}', '{"empress", "femininity", "fertility", "nature"}', '#FFF8E1', '#FBC02D', '#3E2723', '#8D6E63', 'wovenFlower'),
(4, 'The Sovereign', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Sovereign'), '{"Sacred Order", "Boundaries", "Authority Aligned with Truth"}', '{"Domination", "Control", "Distorted Power"}', '{"emperor", "authority", "structure", "control"}', '#FFECB3', '#FFA000', '#4E342E', '#212121', 'crownPyramid'),
(5, 'The Codex', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Codex'), '{"Sacred Knowledge", "Living Archive", "Community Truth"}', '{"Dogma", "Empty Ritual", "Distorted Wisdom"}', '{"hierophant", "tradition", "institution", "belief"}', '#C8E6C9', '#388E3C', '#2E7D32', '#1B5E20', 'codexScroll'),
(6, 'The Union', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Union'), '{"Resonant Alignment", "Sacred Choice", "Harmony"}', '{"Fragmentation", "False Resonance", "Illusionary Connection"}', '{"lovers", "harmony", "relationships", "choices"}', '#F48FB1', '#E91E63', '#880E4F', '#4A148C', 'twinSpirals'),
(7, 'The Flow', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Flow'), '{"Directed Energy", "Sacred Will", "Momentum"}', '{"Chaos", "Loss of Direction", "Forced Control"}', '{"chariot", "willpower", "victory", "assertion"}', '#B2EBF2', '#00ACC1', '#004D40', '#1A237E', 'flowingWave'),
(8, 'The Truth Probe', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Truth Probe'), '{"Clarity", "Distortion Exposure", "Binary Balance"}', '{"Corruption", "Denial", "Hidden Distortion"}', '{"justice", "fairness", "truth", "cause and effect"}', '#ECEFF1', '#90A4AE', '#263238', '#455A64', 'lensTriangle'),
(9, 'The Chamber', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Chamber'), '{"Sacred Sanctuary", "Inner Resonance", "Introspection"}', '{"Isolation", "Withdrawal", "Null Resonance"}', '{"hermit", "introspection", "solitude", "guidance"}', '#D7CCC8', '#795548', '#3E2723', '#212121', 'resonanceShell'),
(10, 'The Wheel of Resonance', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Wheel of Resonance'), '{"Cycles", "Synchronicity", "Sacred Timing"}', '{"Misalignment", "Broken Patterns", "Forced Timing"}', '{"wheel of fortune", "cycles", "luck", "change"}', '#FFF9C4', '#FDD835', '#827717', '#33691E', 'resonanceWheel'),
(11, 'The Breath', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Breath'), '{"Life Force", "Courage", "Sacred Flow"}', '{"Weakness", "Blocked Breath", "Disconnection"}', '{"strength", "courage", "patience", "compassion"}', '#C5CAE9', '#3F51B5', '#1A237E', '#0D47A1', 'breathWave'),
(12, 'The Suspension', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Suspension'), '{"Perspective Shift", "Surrender", "Liminal Awareness"}', '{"Stagnation", "Victimhood", "Avoidance"}', '{"hanged man", "suspension", "new perspective", "sacrifice"}', '#E1BEE7', '#9C27B0', '#4A148C', '#1A237E', 'hangingCross'),
(13, 'The Phoenix Path', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Phoenix Path'), '{"Sacred Ending", "Rebirth", "Transmutation"}', '{"Resistance", "Fear of Change", "False Continuity"}', '{"death", "endings", "transformation", "change"}', '#FFCDD2', '#F44336', '#B71C1C', '#4A148C', 'phoenixFire'),
(14, 'The Harmonic Flow', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Harmonic Flow'), '{"Balance", "Resonant Synthesis", "Sacred Rhythm"}', '{"Imbalance", "Fragmentation", "Clash"}', '{"temperance", "balance", "moderation", "patience"}', '#C8E6C9', '#4CAF50', '#2E7D32', '#1B5E20', 'harmonicBridge'),
(15, 'The Distortion', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Distortion'), '{"Exposure of False Attachments", "Distortion Revealed"}', '{"Entrapment", "Addiction", "Resonance Inversion"}', '{"devil", "bondage", "addiction", "materialism"}', '#F5F5F5', '#9E9E9E', '#212121', '#000000', 'brokenChain'),
(16, 'The Strike', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Strike'), '{"Illumination", "Collapse of False Structures"}', '{"Avoidance", "Hidden Fracture", "Slow Decay"}', '{"tower", "sudden change", "upheaval", "revelation"}', '#FFECB3', '#FFC107', '#E65100', '#BF360C', 'lightningTower'),
(17, 'The Starseed', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Starseed'), '{"Hope", "Cosmic Lineage", "Inspiration"}', '{"Lost Faith", "False Stars", "Distorted Dream"}', '{"star", "hope", "inspiration", "spirituality"}', '#B3E5FC', '#03A9F4', '#01579B', '#0D47A1', 'starseedFlow'),
(18, 'The Dream Veil', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Dream Veil'), '{"Mystery", "Subconscious Flow", "Dream Navigation"}', '{"Confusion", "Projection", "Distorted Illusion"}', '{"moon", "illusion", "fear", "subconscious"}', '#E1BEE7', '#9C27B0', '#6A1B9A', '#311B92', 'veilMoon'),
(19, 'The Sun', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Sun'), '{"Radiance", "Clarity", "Joy in Truth"}', '{"Ego Sun", "False Positivity", "Hollow Light"}', '{"sun", "success", "vitality", "joy"}', '#FFF176', '#FFEB3B', '#F57F17', '#E65100', 'solarBurst'),
(20, 'The Awakening', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Awakening'), '{"Remembrance", "Truth Calling", "Liberation"}', '{"Avoidance", "False Calls", "Denial"}', '{"judgement", "rebirth", "absolution", "inner calling"}', '#FFECB3', '#FF9800', '#BF360C', '#3E2723', 'awakeningHorn'),
(21, 'The Mesh', 'Major', 'Major', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Mesh'), '{"Unity", "Wholeness", "Completion"}', '{"Fragmentation", "False Unity", "Distorted Cycles"}', '{"world", "completion", "integration", "accomplishment"}', '#C8E6C9', '#81C784', '#2E7D32', '#004D40', 'sacredWeb'),
-- Suit of Dream
(22, 'Ace of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Wellspring'), '{"New emotional connection", "Intuitive opening", "Love"}', '{"Blocked emotions", "Emptiness", "Spilled potential"}', '{"love", "emotion", "creativity", "intuition"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-ace'),
(23, 'Two of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Resonant Bond'), '{"Mutual connection", "Partnership", "Shared resonance"}', '{"Imbalance", "Misalignment", "Broken connection"}', '{"partnership", "duality", "connection"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-two'),
(24, 'Three of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Circle of Joy'), '{"Community", "Friendship", "Celebration"}', '{"Isolation", "Gossip", "Exclusivity"}', '{"community", "celebration", "friendship"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-three'),
(25, 'Four of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Still Waters'), '{"Contemplation", "Meditation", "Apathy"}', '{"Restlessness", "Ignoring intuition", "Stagnation"}', '{"apathy", "contemplation", "meditation"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-four'),
(26, 'Five of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Sacred Loss'), '{"Loss", "Grief", "Regret"}', '{"Acceptance", "Moving on", "Finding peace"}', '{"loss", "grief", "disappointment"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-five'),
(27, 'Six of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Echo of Memory'), '{"Nostalgia", "Innocence", "Childhood memories"}', '{"Stuck in the past", "Naivety", "Unrealistic standards"}', '{"nostalgia", "innocence", "childhood"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-six'),
(28, 'Seven of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Vision Quest'), '{"Choices", "Illusion", "Daydreaming"}', '{"Temptation", "Feeling overwhelmed", "Indecision"}', '{"choices", "illusion", "daydreaming"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-seven'),
(29, 'Eight of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Path of Release'), '{"Walking away", "Letting go", "Seeking truth"}', '{"Stagnation", "Fear of change", "Clinging"}', '{"abandonment", "withdrawal", "escapism"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-eight'),
(30, 'Nine of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Wish Fulfilled'), '{"Contentment", "Gratitude", "Wishes fulfilled"}', '{"Smugness", "Dissatisfaction", "Materialism"}', '{"wishes", "contentment", "satisfaction"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-nine'),
(31, 'Ten of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Harmonic Family'), '{"Harmony", "Family", "Fulfillment"}', '{"Broken home", "Dis-harmony", "Misalignment"}', '{"harmony", "family", "fulfillment"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-ten'),
(32, 'Page of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Intuitive Messenger'), '{"Creativity", "Intuitive messages", "Curiosity"}', '{"Emotional immaturity", "Creative block", "Insecurity"}', '{"creative", "intuitive", "emotional"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-page'),
(33, 'Knight of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Romantic Quest'), '{"Romance", "Charm", "Imagination"}', '{"Unrealistic", "Jealousy", "Moodiness"}', '{"romance", "charm", "imagination"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-knight'),
(34, 'Queen of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Compassionate Heart'), '{"Compassion", "Calm", "Intuition"}', '{"Emotional insecurity", "Co-dependency", "Martyrdom"}', '{"compassion", "calm", "intuition"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-queen'),
(35, 'King of Dream', 'Minor', 'Dream', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Emotional Sovereign'), '{"Emotional balance", "Compassion", "Diplomacy"}', '{"Emotional manipulation", "Moodiness", "Volatility"}', '{"balance", "compassion", "diplomacy"}', '#E1F5FE', '#4FC3F7', '#0277BD', '#01579B', 'cup-king'),
-- Suit of Energy
(36, 'Ace of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Spark'), '{"New idea", "Creative spark", "Inspiration"}', '{"Lack of energy", "Creative block", "False start"}', '{"passion", "energy", "creativity", "ambition"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-ace'),
(37, 'Two of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Forked Path'), '{"Planning", "Making decisions", "Future vision"}', '{"Fear of unknown", "Lack of planning", "Indecision"}', '{"planning", "decisions", "future"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-two'),
(38, 'Three of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Expanding Horizon'), '{"Expansion", "Foresight", "Exploration"}', '{"Delays", "Obstacles", "Lack of foresight"}', '{"expansion", "foresight", "exploration"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-three'),
(39, 'Four of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Sacred Celebration'), '{"Celebration", "Harmony", "Community"}', '{"Lack of support", "Instability", "Transition"}', '{"celebration", "harmony", "community"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-four'),
(40, 'Five of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Resonant Clash'), '{"Competition", "Conflict", "Rivalry"}', '{"Avoiding conflict", "Compromise", "Finding common ground"}', '{"competition", "conflict", "rivalry"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-five'),
(41, 'Six of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Victory Lap'), '{"Success", "Public recognition", "Victory"}', '{"Egotism", "Lack of recognition", "Hollow victory"}', '{"success", "recognition", "victory"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-six'),
(42, 'Seven of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Stand for Truth'), '{"Challenge", "Competition", "Perseverance"}', '{"Feeling overwhelmed", "Giving up", "Exhaustion"}', '{"challenge", "perseverance", "defense"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-seven'),
(43, 'Eight of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Swift Current'), '{"Speed", "Action", "Movement"}', '{"Delays", "Frustration", "Rushing"}', '{"speed", "action", "movement"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-eight'),
(44, 'Nine of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Last Stand'), '{"Resilience", "Courage", "Persistence"}', '{"Fatigue", "Defensiveness", "Paranoia"}', '{"resilience", "courage", "persistence"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-nine'),
(45, 'Ten of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Weight of Will'), '{"Burden", "Responsibility", "Hard work"}', '{"Letting go", "Delegating", "Release"}', '{"burden", "responsibility", "work"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-ten'),
(46, 'Page of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Spark of Inspiration'), '{"Enthusiasm", "Exploration", "Discovery"}', '{"Lack of direction", "Procrastination", "Haste"}', '{"enthusiasm", "exploration", "discovery"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-page'),
(47, 'Knight of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Impulsive Force'), '{"Energy", "Passion", "Action"}', '{"Anger", "Impulsiveness", "Recklessness"}', '{"energy", "passion", "action"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-knight'),
(48, 'Queen of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Radiant Leader'), '{"Courage", "Confidence", "Independence"}', '{"Insecurity", "Jealousy", "Demanding"}', '{"courage", "confidence", "independence"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-queen'),
(49, 'King of Energy', 'Minor', 'Energy', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Visionary'), '{"Vision", "Leadership", "Inspiration"}', '{"Tyranny", "Impulsiveness", "Ruthlessness"}', '{"vision", "leadership", "inspiration"}', '#FFF3E0', '#FFB74D', '#F57C00', '#E65100', 'wand-king'),
-- Suit of Truth
(50, 'Ace of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Blade of Clarity'), '{"Breakthrough", "Clarity of thought", "New idea"}', '{"Confusion", "Misinformation", "Mental fog"}', '{"intellect", "truth", "justice", "conflict"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-ace'),
(51, 'Two of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Blind Choice'), '{"Indecision", "Stalemate", "Blocked emotions"}', '{"Difficult choices", "Information overload", "Deceit"}', '{"indecision", "stalemate", "choices"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-two'),
(52, 'Three of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Painful Realization'), '{"Heartbreak", "Sorrow", "Painful truth"}', '{"Recovery", "Forgiveness", "Releasing pain"}', '{"heartbreak", "sorrow", "pain"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-three'),
(53, 'Four of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Sacred Pause'), '{"Rest", "Contemplation", "Meditation"}', '{"Exhaustion", "Burnout", "Stagnation"}', '{"rest", "contemplation", "meditation"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-four'),
(54, 'Five of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Hollow Victory'), '{"Conflict", "Defeat", "Winning at all costs"}', '{"Reconciliation", "Making amends", "Moving on"}', '{"conflict", "defeat", "loss"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-five'),
(55, 'Six of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Journey to Clarity'), '{"Transition", "Moving on", "Rite of passage"}', '{"Unfinished business", "Resistance to change", "Baggage"}', '{"transition", "moving on", "journey"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-six'),
(56, 'Seven of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Shadow Self'), '{"Deception", "Betrayal", "Theft"}', '{"Confession", "Facing truth", "Reclaiming power"}', '{"deception", "betrayal", "theft"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-seven'),
(57, 'Eight of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Mental Prison'), '{"Imprisonment", "Restriction", "Victim mentality"}', '{"Freedom", "Release", "Taking control"}', '{"imprisonment", "restriction", "victim"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-eight'),
(58, 'Nine of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Dark Night of the Soul'), '{"Anxiety", "Fear", "Nightmares"}', '{"Facing fears", "Finding hope", "Release from anxiety"}', '{"anxiety", "fear", "nightmares"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-nine'),
(59, 'Ten of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Final Cut'), '{"Painful endings", "Betrayal", "Rock bottom"}', '{"Recovery", "Resurrection", "New beginnings"}', '{"endings", "betrayal", "rock bottom"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-ten'),
(60, 'Page of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Curious Mind'), '{"Curiosity", "New ideas", "Thirst for knowledge"}', '{"Gossip", "Deception", "Scattered thoughts"}', '{"curiosity", "ideas", "knowledge"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-page'),
(61, 'Knight of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Unrelenting Force'), '{"Ambition", "Action", "Assertiveness"}', '{"Rudeness", "Aggression", "Haste"}', '{"ambition", "action", "assertiveness"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-knight'),
(62, 'Queen of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Clear Judge'), '{"Clarity", "Independence", "Unbiased judgment"}', '{"Coldness", "Bitterness", "Cruelty"}', '{"clarity", "independence", "judgment"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-queen'),
(63, 'King of Truth', 'Minor', 'Truth', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Intellectual Sovereign'), '{"Intellect", "Authority", "Truth"}', '{"Manipulation", "Cruelty", "Abuse of power"}', '{"intellect", "authority", "truth"}', '#E8EAF6', '#9FA8DA', '#3F51B5', '#1A237E', 'sword-king'),
-- Suit of Community
(64, 'Ace of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Seed of Prosperity'), '{"New opportunity", "Manifestation", "Prosperity"}', '{"Missed opportunity", "Scarcity mindset", "Greed"}', '{"manifestation", "prosperity", "security", "community"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-ace'),
(65, 'Two of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Juggler'), '{"Balance", "Prioritization", "Adaptability"}', '{"Imbalance", "Disorganization", "Overwhelmed"}', '{"balance", "prioritization", "adaptability"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-two'),
(66, 'Three of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Master Craftsman'), '{"Teamwork", "Collaboration", "Skill"}', '{"Lack of teamwork", "Poor quality", "Mediocrity"}', '{"teamwork", "collaboration", "skill"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-three'),
(67, 'Four of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Guardian of Gifts'), '{"Security", "Conservation", "Stability"}', '{"Greed", "Materialism", "Hoarding"}', '{"security", "conservation", "stability"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-four'),
(68, 'Five of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Outsider'), '{"Hardship", "Poverty", "Isolation"}', '{"Recovery", "Finding help", "Community support"}', '{"hardship", "poverty", "isolation"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-five'),
(69, 'Six of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Giver and Receiver'), '{"Generosity", "Charity", "Sharing"}', '{"Debt", "Selfishness", "One-sided charity"}', '{"generosity", "charity", "sharing"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-six'),
(70, 'Seven of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Patient Gardener'), '{"Patience", "Investment", "Long-term vision"}', '{"Impatience", "Lack of vision", "Wasted effort"}', '{"patience", "investment", "vision"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-seven'),
(71, 'Eight of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Diligent Apprentice'), '{"Apprenticeship", "Skill development", "Diligence"}', '{"Perfectionism", "Lack of ambition", "Repetitive work"}', '{"apprenticeship", "skill", "diligence"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-eight'),
(72, 'Nine of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Sovereign Steward'), '{"Abundance", "Independence", "Self-sufficiency"}', '{"Financial dependency", "Superficiality", "Living beyond means"}', '{"abundance", "independence", "sufficiency"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-nine'),
(73, 'Ten of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Legacy'), '{"Legacy", "Inheritance", "Family wealth"}', '{"Family disputes", "Financial failure", "Fleeting success"}', '{"legacy", "inheritance", "wealth"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-ten'),
(74, 'Page of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Eager Student'), '{"Manifestation", "New opportunities", "Learning"}', '{"Lack of commitment", "Procrastination", "Missed opportunities"}', '{"manifestation", "opportunity", "learning"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-page'),
(75, 'Knight of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Reliable Worker'), '{"Hard work", "Responsibility", "Diligence"}', '{"Laziness", "Irresponsibility", "Stagnation"}', '{"work", "responsibility", "diligence"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-knight'),
(76, 'Queen of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Nurturing Provider'), '{"Nurturing", "Practicality", "Security"}', '{"Smothering", "Financial insecurity", "Self-care neglect"}', '{"nurturing", "practicality", "security"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-queen'),
(77, 'King of Community', 'Minor', 'Community', (SELECT id FROM public.tarot_archetypes WHERE name = 'The Abundant King'), '{"Abundance", "Prosperity", "Security"}', '{"Greed", "Corruption", "Materialistic"}', '{"abundance", "prosperity", "security"}', '#E8F5E9', '#A5D6A7', '#43A047', '#1B5E20', 'pentacle-king')
ON CONFLICT (id) DO NOTHING;
