-- Create the tarot_journal_logs table
CREATE TABLE public.tarot_journal_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    card_id INT NOT NULL,
    is_reversed BOOLEAN NOT NULL,
    interpretation TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.tarot_journal_logs ENABLE ROW LEVEL SECURITY;

-- Create policy for users to view their own logs
CREATE POLICY "Allow users to view their own logs"
ON public.tarot_journal_logs
FOR SELECT
USING (auth.uid() = user_id);

-- Create policy for users to insert their own logs
CREATE POLICY "Allow users to insert their own logs"
ON public.tarot_journal_logs
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Create policy for users to update their own logs
CREATE POLICY "Allow users to update their own logs"
ON public.tarot_journal_logs
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Create policy for users to delete their own logs
CREATE POLICY "Allow users to delete their own logs"
ON public.tarot_journal_logs
FOR DELETE
USING (auth.uid() = user_id);

-- Add comments to the table and columns
COMMENT ON TABLE public.tarot_journal_logs IS 'Stores tarot card pulls and journal entries from users.';
COMMENT ON COLUMN public.tarot_journal_logs.card_id IS 'The ID of the tarot card pulled, mapping to the application''s internal deck data.';
COMMENT ON COLUMN public.tarot_journal_logs.is_reversed IS 'Whether the card was drawn in a reversed position.';
COMMENT ON COLUMN public.tarot_journal_logs.interpretation IS 'The user''s personal interpretation or notes on the card pull.';
